#!/bin/bash

# 创建缓存目录
CACHE_DIR="./docker/package_cache"
mkdir -p "$CACHE_DIR"

echo "开始下载系统包到本地缓存..."

# 下载Debian包
cd "$CACHE_DIR"

# 基础包列表
PACKAGES=(
    "gcc"
    "g++"
    "libpq-dev"
    "curl"
    "wget"
    "gnupg"
    "fonts-unifont"
    "fonts-liberation"
    # Playwright需要的完整X11和图形库
    "libgobject-2.0-0"
    "libglib2.0-0"
    "libnss3"
    "libnspr4"
    "libdbus-1-3"
    "libatk1.0-0"
    "libatk-bridge2.0-0"
    "libcups2"
    "libdrm2"
    "libexpat1"
    "libxcb1"
    "libxkbcommon0"
    "libatspi2.0-0"
    "libx11-6"
    "libxcomposite1"
    "libxdamage1"
    "libxext6"
    "libxfixes3"
    "libxrandr2"
    "libgbm1"
    "libpango-1.0-0"
    "libcairo2"
    "libasound2"
    # 其他必需的库
    "libdrm-amdgpu1"
    "libdrm-intel1"
    "libpciaccess0"
    "libedit2"
    "libelf1t64"
    "libfribidi0"
    "libwayland-server0"
    "libxml2"
    "libz3-4"
    "libllvm19"
    "libsensors-config"
    "libsensors5"
    "libx11-xcb1"
    "libxcb-dri3-0"
    "libxcb-present0"
    "libxcb-randr0"
    "libxcb-render0"
    "libxcb-shm0"
    "libxcb-sync1"
    "libxcb-xfixes0"
    "libxshmfence1"
    "mesa-libgallium"
    "libglib2.0-data"
    "libgraphite2-3"
    "libharfbuzz0b"
    "libkmod2"
    "libthai-data"
    "libthai0"
    "xkb-data"
    "psmisc"
    "shared-mime-info"
    "systemd-cryptsetup"
    "xdg-user-dirs"
    # 系统服务
    "systemd"
    "systemd-sysv"
    "dbus"
    "dbus-bin"
    "dbus-daemon"
    "dbus-session-bus-common"
    "dbus-system-bus-common"
    "dbus-user-session"
    "procps"
    "libnss-systemd"
    "libpam-systemd"
    "systemd-timesyncd"
    # 音频支持
    "alsa-topology-conf"
    "alsa-ucm-conf"
    "libasound2-data"
    # 字体支持
    "fontconfig"
    "fontconfig-config"
    "fonts-dejavu-core"
    "fonts-dejavu-mono"
    "libfontconfig1"
    "libfreetype6"
    # 其他支持库
    "at-spi2-common"
    "at-spi2-core"
    "dconf-gsettings-backend"
    "dconf-service"
    "dmsetup"
    "gsettings-desktop-schemas"
    "libapparmor1"
    "libavahi-client3"
    "libavahi-common-data"
    "libavahi-common3"
    "libcryptsetup12"
    "libdatrie1"
    "libdconf1"
    "libdevmapper1.02.1"
    "libjson-c5"
    "libpng16-16t64"
    "libproc2-0"
    "libsystemd-shared"
    "libthai-data"
    "libthai0"
    "libxau6"
    "libxdmcp6"
    "libxi6"
    "libxtst6"
    "linux-sysctl-defaults"
    "x11-common"
)

# 使用apt-get download下载包
echo "下载Debian包..."
apt-get download "${PACKAGES[@]}"

echo "包下载完成！缓存目录: $CACHE_DIR"
echo "下载的包数量: $(ls -1 *.deb 2>/dev/null | wc -l)"
